type Message {
  id: Int!
  body: String!
  title: String
  user: String
  createdAt: String!
}

input MessageSendInput {
  body: String!
  title: String
}

type Query {
  MessageList: [Message!]!
}

type Mutation {
  MessageSend(message: MessageSendInput): Message
}
